<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sm</string>
	</array>
	<key>name</key>
	<string>SLICC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.desc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.desc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/[*]</string>
			<key>end</key>
			<string>[*]/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(external_type).*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>external_type</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*([a-zA-Z0-9_]+)\s+([a-zA-Z0-9_]+)\((.*)\);</string>
					<key>name</key>
					<string>function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(structure).*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>structure</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>text.plain</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*([a-zA-Z0-9_]+)\s+([a-zA-Z0-9_]+).*(desc)=(".*");</string>
					<key>name</key>
					<string>members</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(machine|structure|enumeration|external_type)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(desc|format|default|network|virtual_network|ordered|interface|template_hack|constructor_hack|vnet_type)\b</string>
			<key>name</key>
			<string>support.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(action|transition|trigger|error|peek|assert|DEBUG_EXPR|enqueue|dequeue|in_port|out_port)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|return|switch|else)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(string|bool|void)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.slicc</string>
	<key>uuid</key>
	<string></string>
</dict>
</plist>
